
-----------下方装备自定义添加删除（打开配置目录，再配置文件中可以直接复制装备名字）--------------
item_wear("上位迷你大象帽子")
sleep(10)
item_wear("上位迷你大象上衣")
sleep(10)
item_wear("上位迷你大象下衣")
sleep(10)
item_wear("上位迷你大象鞋子")
sleep(10)
item_wear("LA穿越系列-手心的你(男)手套")
sleep(10)
item_wear("龙晶[魔龙影]")
sleep(10)
item_wear("元素之声+4")
sleep(10)
item_wear("迪特徽章+3") --经验徽章
sleep(10)
item_wear("愤怒的阿拉斯托 戒指")
sleep(10)
item_wear("天空之城耳环")
sleep(10)